package diffx

import (
	"sort"
	"strings"

	"github.com/matteo-sung/lockvet/internal/lock"
)

// migrationThreshold: when at least this many packages in one lockfile move
// between the SAME two registry hosts, that is a registry/mirror migration
// (a config change), not a per-package attack — the per-package
// registry-moved flag is suppressed for that pair. Dependency-confusion
// attacks move one package, or very few.
const migrationThreshold = 5

type hostPair struct{ old, new string }

// countHostMoves tallies, per (oldHost → newHost) pair, how many packages in
// the file moved between those hosts — including packages whose versions
// didn't change, which never become diff rows.
func countHostMoves(oldF, newF *lock.File) map[hostPair]int {
	if oldF == nil || newF == nil || oldF.Pins == nil || newF.Pins == nil {
		return nil
	}
	counts := map[hostPair]int{}
	for name, oldVers := range oldF.Packages {
		newVers, ok := newF.Packages[name]
		if !ok {
			continue
		}
		oh := commonHost(oldF, name, oldVers)
		nh := commonHost(newF, name, newVers)
		if oh != "" && nh != "" && oh != nh {
			counts[hostPair{oh, nh}]++
		}
	}
	return counts
}

// commonHost returns the registry host recorded for the package if every
// version that records one agrees; "" otherwise.
func commonHost(f *lock.File, name string, versions []string) string {
	host := ""
	for _, v := range versions {
		h := f.Pin(name, v).Host
		if h == "" {
			continue
		}
		if host == "" {
			host = h
		} else if host != h {
			return ""
		}
	}
	return host
}

// countIntegrityLosses tallies how many packages in the file lost every
// recorded content hash on a version pinned on both sides (packages the
// new side marks non-registry excluded — git/path overrides record a
// commit, not a registry hash). One or two losses is the tamper shape;
// at or above migrationThreshold the file was regenerated by tooling
// that writes no hashes, and the per-package flag is suppressed.
func countIntegrityLosses(oldF, newF *lock.File) int {
	if oldF == nil || newF == nil || oldF.Pins == nil {
		return 0
	}
	n := 0
	for name, oldVers := range oldF.Packages {
		newVers, ok := newF.Packages[name]
		if !ok || newF.NonRegistry[name] {
			continue
		}
		in := map[string]bool{}
		for _, v := range newVers {
			in[v] = true
		}
		for _, v := range oldVers {
			if in[v] && integrityLost(oldF.Pin(name, v).Integrity, newF.Pin(name, v).Integrity) {
				n++
				break
			}
		}
	}
	return n
}

// integrityLost reports whether a pin that carried at least one
// recognized content hash before carries none now — either the hash was
// deleted outright or replaced with a value no algorithm claims.
func integrityLost(oi, ni string) bool {
	return len(hashesByAlgo(oi)) > 0 && len(hashesByAlgo(ni)) == 0
}

// annotatePinChange fills integrity/host findings on one change. Returns
// true when it found something row-worthy (used to surface same-version
// repins that would otherwise not be diff rows).
func annotatePinChange(c *Change, oldF, newF *lock.File, moves map[hostPair]int, intLosses int) bool {
	if oldF == nil || newF == nil {
		return false // added/removed files: nothing to compare against
	}
	name := c.Name
	if sideEco(oldF, name) != sideEco(newF, name) {
		// The package switched package managers between the two sides
		// (pixi/conda locks: a conda package became a PyPI wheel or vice
		// versa). Hashes and hosts legitimately change wholesale.
		return false
	}
	// Integrity: compare versions present on both sides.
	common := intersectVersions(c.Old, c.New)
	sameBytesProven := len(common) > 0
	for _, v := range common {
		oi := oldF.Pin(name, v).Integrity
		ni := newF.Pin(name, v).Integrity
		if integrityLost(oi, ni) {
			eco := lock.Ecosystem(c.Ecosystem)
			// Docker/Conan digests move (and get unpinned) by design —
			// their neutral digest lane applies, not an alarm. Packages
			// the new side marks non-registry switched to a git/path
			// source: the pin moved to a commit, hashes legitimately
			// vanish. At migrationThreshold losses the whole file was
			// regenerated by tooling that writes no hashes.
			if eco != lock.Docker && eco != lock.Conan &&
				!newF.NonRegistry[name] && intLosses < migrationThreshold {
				c.IntegrityRemoved = true
				c.IntegrityRemovedVersions = append(c.IntegrityRemovedVersions, v)
			}
		}
		if oi == "" || ni == "" {
			sameBytesProven = false
			continue
		}
		if integrityDiffers(oi, ni) {
			eco := lock.Ecosystem(c.Ecosystem)
			if eco == lock.Docker || eco == lock.Conan {
				// Image tags move by design: registries rebuild the same
				// tag for base-image security fixes, and digest-update
				// PRs re-pin it. Not an integrity alarm — record the
				// digests so the row renders neutrally and the ocireg
				// layer can verify the NEW pin against the registry.
				// Conan recipe revisions are the same shape: the rrev
				// hashes the recipe (the build script), and ConanCenter
				// re-exports recipes for old versions routinely — a
				// same-version rrev change is worth SEEING (silence was
				// the old behaviour) but not worth an alarm, and the
				// lockfile never records which remote it came from, so
				// no registry verification is honest here.
				c.DigestChanged = true
				c.OldDigest, c.NewDigest = firstHash(oi), firstHash(ni)
			} else {
				c.IntegrityChanged = true
				c.IntegrityVersions = append(c.IntegrityVersions, v)
			}
		}
		if !integritySame(oi, ni) {
			sameBytesProven = false
		}
	}
	sort.Strings(c.IntegrityVersions)
	sort.Strings(c.IntegrityRemovedVersions)

	// Resolution host.
	oh := commonHost(oldF, name, c.Old)
	nh := commonHost(newF, name, c.New)
	if oh != "" && nh != "" && oh != nh {
		c.OldHost, c.NewHost = oh, nh
		eco := lock.Ecosystem(c.Ecosystem)
		switch {
		case eco == lock.Nix || eco == lock.Zig || eco == lock.Vcpkg:
			// Flake and build.zig.zon "hosts" are whole source locations
			// (forge repo paths, mirror hostnames): a host move means the
			// dependency was re-pointed at a different source — the
			// no-registry shape of a hijacked resolution. Content proven
			// identical (same hash) stays quiet. For Zig only same-version
			// moves alarm: build.zig.zon is hand-edited, and swapping a
			// dependency to a fork or mirror WITH a new pin is routine,
			// visible business (a fifth of real ghostty/libvaxis history);
			// a source that changes while the version claims nothing moved
			// is the shape worth stopping for. For vcpkg the host is the
			// registry repository a default-registry baseline resolves
			// from: a swap re-points EVERY dependency's version source.
			// Even a same-commit swap flags (as a repin): today's content
			// is sha-identical, but every FUTURE baseline bump would come
			// from the new repository — the setup step of the attack.
			if eco == lock.Zig && len(common) == 0 {
				break
			}
			if moves[hostPair{oh, nh}] < migrationThreshold && !sameBytesProven {
				c.RegistryMoved = true
			}
		case eco.PublicRegistryHost(nh) && !eco.PublicRegistryHost(oh) &&
			moves[hostPair{oh, nh}] < migrationThreshold && !sameBytesProven:
			c.RegistryMoved = true
		}
	}
	return c.IntegrityChanged || c.IntegrityRemoved || c.RegistryMoved || c.DigestChanged
}

// firstHash returns the first hash in a space-joined set (container
// image pins record exactly one digest per (name, tag)).
func firstHash(set string) string {
	f := strings.Fields(set)
	if len(f) == 0 {
		return ""
	}
	return f[0]
}

// sideEco is the ecosystem one side resolves the package with (per-package
// override for SBOM / conda+pip mixed files, else the file's ecosystem).
func sideEco(f *lock.File, name string) lock.Ecosystem {
	if e, ok := f.PkgEco[name]; ok {
		return e
	}
	return f.Ecosystem
}

// intersectVersions returns versions present in both lists (set semantics).
func intersectVersions(a, b []string) []string {
	if len(a) == 0 || len(b) == 0 {
		return nil
	}
	in := map[string]bool{}
	for _, v := range a {
		in[v] = true
	}
	var out []string
	seen := map[string]bool{}
	for _, v := range b {
		if in[v] && !seen[v] {
			out = append(out, v)
			seen[v] = true
		}
	}
	return out
}

// integrityDiffers compares two hash sets algorithm-by-algorithm. Only
// algorithms present on BOTH sides are compared, so a lockfile-format
// upgrade that switches sha1 → sha512 (or yarn berry's cache-key bumps)
// never flags. Within a shared algorithm, any overlapping hash means the
// same artifact is still acceptable — Python lockfiles legitimately GROW
// the hash set when new wheels are added for an existing release.
// integrityDiffers reports whether the two hash sets disagree about the
// pinned artifact. Each shared algorithm is judged on its own: a hash
// function is deterministic, so the same artifact can never carry two
// different values under one algorithm — a shared algorithm whose sets
// are fully disjoint proves the integrity claim changed, no matter what
// any OTHER algorithm says. (The logic this replaces pooled overlap
// across algorithms: a yarn-classic pin whose SRI sha512 was swapped
// compared as "no changes" because the untouched sha1 `resolved`
// fragment still overlapped — exactly the poisoned-checksum camouflage
// this lane exists to catch, since yarn verifies the SRI line at
// install time, not the fragment.)
//
// Two shapes keep pooled/scoped semantics:
//   - artifact-scoped sets ("file.jar#sha256:…", Gradle verification
//     metadata): already per-file, disjoint-per-scope flags as before.
//   - Terraform h1/zh: h1 hashes exist only for the platforms the lock
//     was built with — re-locking for a different platform legitimately
//     replaces the whole h1 set while the registry-published zh set
//     (every release file) still overlaps. zh overlap vouches for the
//     release; h1 disjointness there is platform selection, not tamper.
func integrityDiffers(oldSet, newSet string) bool {
	oldBy := hashesByAlgo(oldSet)
	newBy := hashesByAlgo(newSet)
	pooledShared, pooledOverlap := false, false
	for algo, oldHashes := range oldBy {
		newHashes, ok := newBy[algo]
		if !ok {
			continue // algo upgrades / added artifacts never flag
		}
		overlap := false
		for h := range oldHashes {
			if newHashes[h] {
				overlap = true
				break
			}
		}
		if platformScopedAlgo(algo) {
			pooledShared = true
			if overlap {
				pooledOverlap = true
			}
			continue
		}
		if !overlap {
			return true // fully disjoint under a shared algorithm → changed
		}
	}
	return pooledShared && !pooledOverlap
}

// platformScopedAlgo marks hash families whose membership depends on
// which platforms the lock was generated for (Terraform), so a wholesale
// set replacement under ONE family is explained by the other family's
// overlap rather than contradicted by it.
func platformScopedAlgo(algo string) bool { return algo == "h1" || algo == "zh" }

// integritySame reports whether the two hash sets prove the same artifact
// is referenced: at least one (algorithm, hash) pair is shared AND no
// shared algorithm contradicts it — a shared-yet-disjoint algorithm means
// one side's claim is wrong, and overlap elsewhere proves nothing then.
func integritySame(oldSet, newSet string) bool {
	oldBy := hashesByAlgo(oldSet)
	newBy := hashesByAlgo(newSet)
	found := false
	for algo, oldHashes := range oldBy {
		for h := range oldHashes {
			if newBy[algo][h] {
				found = true
			}
		}
	}
	return found && !integrityDiffers(oldSet, newSet)
}

// hashesByAlgo groups a space-joined hash set by algorithm label.
// Recognized notations: "sha512-…" (npm SRI), "sha256:…" (Python/OCI),
// "10c0/…" (yarn berry cache key), bare 40-hex (sha1), bare 64-hex (sha256).
func hashesByAlgo(set string) map[string]map[string]bool {
	out := map[string]map[string]bool{}
	for _, h := range strings.Fields(set) {
		algo, val := splitHash(h)
		if algo == "" || val == "" {
			continue
		}
		if out[algo] == nil {
			out[algo] = map[string]bool{}
		}
		out[algo][val] = true
	}
	return out
}

func splitHash(h string) (algo, val string) {
	// Artifact-scoped notation "file.jar#sha256:hex" (Gradle verification
	// metadata records several artifacts per component; each file's hash
	// set is compared on its own).
	if i := strings.IndexByte(h, '#'); i > 0 && i < len(h)-1 {
		algo, val = splitHash(h[i+1:])
		if algo == "" {
			return "", ""
		}
		return h[:i] + "#" + algo, val
	}
	for _, sep := range []byte{'-', ':', '/'} {
		if i := strings.IndexByte(h, sep); i > 0 {
			// require a plausible algorithm label, not a hash that merely
			// contains the separator (npm SRI base64 contains '-')
			label := strings.ToLower(h[:i])
			if len(label) <= 12 && isAlgoLabel(label) {
				return label, h[i+1:]
			}
		}
	}
	if isHex(h) {
		switch len(h) {
		case 40:
			return "sha1", h
		case 64:
			return "sha256", h
		case 128:
			return "sha512", h
		}
	}
	return "", ""
}

// isAlgoLabel accepts lowercase alphanumerics plus underscore so hashlib/
// PyPI algorithm names (sha3_256, shake_128, blake2b_256) label properly;
// without this a pylock entry hashed only with such an algorithm carried
// no comparable integrity at all. The 12-char cap (at the call site) keeps
// base64 hash values that merely contain a separator from masquerading as
// labels.
func isAlgoLabel(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if !(c >= 'a' && c <= 'z' || c >= '0' && c <= '9' || c == '_') {
			return false
		}
	}
	return true
}

func isHex(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f' || c >= 'A' && c <= 'F') {
			return false
		}
	}
	return true
}
