package lock

import (
	"reflect"
	"sort"
	"testing"
)

func TestCondaNV(t *testing.T) {
	cases := []struct{ url, name, version string }{
		{"https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.46.1-default_hbd61a6d_102.conda", "ld_impl_linux-64", "2.46.1"},
		{"https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2", "_libgcc_mutex", "0.1"},
		{"https://prefix.dev/conda-forge/noarch/tzdata-2026c-h8d34b9e_0.conda", "tzdata", "2026c"},
		{"https://conda.anaconda.org/conda-forge/noarch/antlr-python-runtime-4.9.3-pyhd8ed1ab_1.tar.bz2", "antlr-python-runtime", "4.9.3"},
		{"https://example.com/no-suffix", "", ""},
		{"https://example.com/short.conda", "", ""},
	}
	for _, c := range cases {
		n, v := condaNV(c.url)
		if n != c.name || v != c.version {
			t.Errorf("condaNV(%s) = %q %q, want %q %q", c.url, n, v, c.name, c.version)
		}
	}
}

func TestPixiLockV7(t *testing.T) {
	f := mustParse(t, "pixi.lock", `version: 7
platforms:
- name: linux-64
  virtual-packages:
  - __unix=0=0
environments:
  default:
    channels:
    - url: https://prefix.dev/conda-forge/
    packages:
      linux-64:
      - conda: https://prefix.dev/conda-forge/linux-64/libgomp-15.2.0-he0feb66_19.conda
packages:
- conda: https://prefix.dev/conda-forge/linux-64/_openmp_mutex-4.5-20_gnu.conda
  build_number: 20
  sha256: abc
  depends:
  - __glibc >=2.17,<3.0.a0
  - libgomp >=7.5.0
  license: BSD-3-Clause
  run_exports:
    strong:
    - _openmp_mutex >=4.5
  size: 28948
- conda: https://prefix.dev/conda-forge/linux-64/libgomp-15.2.0-he0feb66_19.conda
  depends:
  - __glibc >=2.17
  license: GPL-3.0-only WITH GCC-exception-3.1
- pypi: https://files.pythonhosted.org/packages/aa/bb/tzdata-2025.1-py2.py3-none-any.whl
  name: tzdata
  version: '2025.1'
  sha256: def
  requires_python: '>=2'
- pypi: https://files.pythonhosted.org/packages/cc/dd/pandas_stubs-2.2.0-py3-none-any.whl
  name: pandas_stubs
  version: 2.2.0
  requires_dist:
  - tzdata>=2022.7
  - numpy ; extra == 'x'
- pypi: .
  name: myproject
  requires_dist:
  - tzdata
`)
	wantPkgs(t, f, map[string][]string{
		"_openmp_mutex": {"4.5"},
		"libgomp":       {"15.2.0"},
		"tzdata":        {"2025.1"},
		"pandas_stubs":  {"2.2.0"},
	})
	if f.PkgEco["tzdata"] != PyPI || f.PkgEco["pandas_stubs"] != PyPI {
		t.Errorf("PkgEco = %v, want tzdata and pandas_stubs marked PyPI", f.PkgEco)
	}
	if _, ok := f.PkgEco["libgomp"]; ok {
		t.Errorf("libgomp should stay conda, got %v", f.PkgEco["libgomp"])
	}
	// __glibc virtual is skipped; run_exports nested list is not a depends.
	if got := f.Deps["_openmp_mutex"]; !reflect.DeepEqual(got, []string{"libgomp"}) {
		t.Errorf("_openmp_mutex deps = %v, want [libgomp]", got)
	}
	// requires_dist edge with PEP 503 normalization (pandas_stubs → tzdata).
	if got := f.Deps["pandas_stubs"]; !reflect.DeepEqual(got, []string{"tzdata"}) {
		t.Errorf("pandas_stubs deps = %v, want [tzdata]", got)
	}
	if f.RootsKnown {
		t.Error("pixi.lock records no roots; RootsKnown must be false")
	}
}

func TestPixiLockV4(t *testing.T) {
	f := mustParse(t, "pixi.lock", `version: 4
environments:
  default:
    channels:
    - url: https://conda.anaconda.org/conda-forge/
    packages:
      linux-64:
      - conda: https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-2_gnu.tar.bz2
packages:
- kind: conda
  name: _openmp_mutex
  version: '4.5'
  build: 2_gnu
  subdir: linux-64
  url: https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-2_gnu.tar.bz2
  depends:
  - _libgcc_mutex 0.1 conda_forge
  - libgomp >=7.5.0
  license: BSD-3-Clause
- kind: conda
  name: libgomp
  version: 13.2.0
  url: https://conda.anaconda.org/conda-forge/linux-64/libgomp-13.2.0-h807b86a_5.conda
- kind: conda
  name: _libgcc_mutex
  version: '0.1'
  url: https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
- kind: pypi
  name: requests
  version: 2.31.0
  url: https://files.pythonhosted.org/packages/x/requests-2.31.0-py3-none-any.whl
  requires_dist:
  - charset-normalizer <4,>=2
`)
	wantPkgs(t, f, map[string][]string{
		"_openmp_mutex": {"4.5"},
		"libgomp":       {"13.2.0"},
		"_libgcc_mutex": {"0.1"},
		"requests":      {"2.31.0"},
	})
	if f.PkgEco["requests"] != PyPI {
		t.Errorf("requests eco = %v, want PyPI", f.PkgEco["requests"])
	}
	got := append([]string(nil), f.Deps["_openmp_mutex"]...)
	sort.Strings(got)
	if !reflect.DeepEqual(got, []string{"_libgcc_mutex", "libgomp"}) {
		t.Errorf("_openmp_mutex deps = %v", got)
	}
}

func TestCondaLockYml(t *testing.T) {
	f := mustParse(t, "conda-lock.yml", `# This lock file was generated by conda-lock.  DO NOT EDIT!
version: 1
metadata:
  content_hash:
    linux-64: abc
  channels:
  - url: conda-forge
    used_env_vars: []
  platforms:
  - linux-64
  - osx-arm64
package:
- name: _openmp_mutex
  version: '4.5'
  manager: conda
  platform: linux-64
  dependencies:
    _libgcc_mutex: '0.1'
    libgomp: '>=7.5.0'
  url: https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-2_gnu.tar.bz2
  hash:
    md5: abc123
    sha256: def456
  category: main
  optional: false
- name: libgomp
  version: 14.2.0
  manager: conda
  platform: linux-64
  dependencies: {}
  url: https://conda.anaconda.org/conda-forge/linux-64/libgomp-14.2.0-h77fa898_1.conda
  hash:
    md5: aaa
  category: main
  optional: false
- name: libgomp
  version: 14.2.0
  manager: conda
  platform: osx-arm64
  dependencies: {}
  url: https://conda.anaconda.org/conda-forge/osx-arm64/libgomp-14.2.0-h0a1ffab_1.conda
  hash:
    md5: bbb
  category: main
  optional: false
- name: _libgcc_mutex
  version: '0.1'
  manager: conda
  platform: linux-64
  dependencies: {}
  url: https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
  hash:
    md5: ccc
  category: main
  optional: false
- name: streamdeck
  version: 0.9.5
  manager: pip
  platform: linux-64
  dependencies:
    typing-extensions: '*'
  url: https://files.pythonhosted.org/packages/5b/streamdeck-0.9.5-py3-none-any.whl
  hash:
    sha256: eee
  category: main
  optional: false
- name: typing_extensions
  version: 4.12.2
  manager: pip
  platform: linux-64
  dependencies: {}
  url: https://files.pythonhosted.org/packages/ty/typing_extensions-4.12.2-py3-none-any.whl
  hash:
    sha256: fff
  category: main
  optional: false
`)
	wantPkgs(t, f, map[string][]string{
		"_openmp_mutex":     {"4.5"},
		"libgomp":           {"14.2.0"}, // two platforms, one version: deduped
		"_libgcc_mutex":     {"0.1"},
		"streamdeck":        {"0.9.5"},
		"typing_extensions": {"4.12.2"},
	})
	if f.PkgEco["streamdeck"] != PyPI || f.PkgEco["typing_extensions"] != PyPI {
		t.Errorf("PkgEco = %v, want pip packages marked PyPI", f.PkgEco)
	}
	if _, ok := f.PkgEco["libgomp"]; ok {
		t.Error("conda package libgomp must not be marked PyPI")
	}
	got := append([]string(nil), f.Deps["_openmp_mutex"]...)
	sort.Strings(got)
	if !reflect.DeepEqual(got, []string{"_libgcc_mutex", "libgomp"}) {
		t.Errorf("_openmp_mutex deps = %v", got)
	}
	// hash: md5 keys must not leak into the graph.
	for from, deps := range f.Deps {
		for _, d := range deps {
			if d == "md5" || d == "sha256" || d == "abc123" {
				t.Errorf("hash key leaked into graph: %s -> %s", from, d)
			}
		}
	}
	// pip dependencies resolve with PEP 503 normalization.
	if got := f.Deps["streamdeck"]; !reflect.DeepEqual(got, []string{"typing_extensions"}) {
		t.Errorf("streamdeck deps = %v, want [typing_extensions]", got)
	}
}

func TestCondaSuffixNames(t *testing.T) {
	for name, kind := range map[string]string{
		"audio.pixi.lock":                "pixi.lock",
		"conda-reqs.conda-lock.yml":      "conda-lock.yml",
		"buildenv.conda-lock.yaml":       "conda-lock.yml",
		"pixi.lock":                      "pixi.lock",
		"conda-lock.yaml":                "conda-lock.yml",
		"some/dir/nested.pixi.lock":      "pixi.lock",
		"conda-reqs/reqs.conda-lock.yml": "conda-lock.yml",
		"not-a-pixi.lock.txt":            "",
		"pixi.lock.template":             "",
		"environment.yml":                "",
	} {
		p := ByBasename(name)
		switch {
		case kind == "" && p != nil:
			t.Errorf("%s: expected no parser, got %s", name, p.Kind)
		case kind != "" && (p == nil || p.Kind != kind):
			t.Errorf("%s: expected %s, got %v", name, kind, p)
		}
	}
}
