package lock

import (
	"reflect"
	"sort"
	"testing"
)

func wantRoots(t *testing.T, f *File, roots ...string) {
	t.Helper()
	if !f.RootsKnown {
		t.Fatalf("%s: RootsKnown = false, want true", f.Kind)
	}
	got := append([]string(nil), f.Roots...)
	sort.Strings(got)
	sort.Strings(roots)
	if !reflect.DeepEqual(got, roots) {
		t.Errorf("%s: roots = %v, want %v", f.Kind, got, roots)
	}
}

func wantEdge(t *testing.T, f *File, from, to string) {
	t.Helper()
	for _, d := range f.Deps[from] {
		if d == to {
			return
		}
	}
	t.Errorf("%s: missing edge %s -> %s (deps: %v)", f.Kind, from, to, f.Deps[from])
}

func TestPackageLockV3Graph(t *testing.T) {
	f := parseWith(t, "package-lock.json", `{
	  "lockfileVersion": 3,
	  "packages": {
	    "": {"name": "root", "dependencies": {"express": "^4"}, "devDependencies": {"jest": "^29"}},
	    "node_modules/express": {"version": "4.17.1", "dependencies": {"debug": "2.6.9"}},
	    "node_modules/debug": {"version": "2.6.9", "dependencies": {"ms": "2.0.0"}},
	    "node_modules/ms": {"version": "2.0.0"},
	    "node_modules/jest": {"version": "29.0.0"}
	  }
	}`)
	wantRoots(t, f, "express", "jest")
	wantEdge(t, f, "express", "debug")
	wantEdge(t, f, "debug", "ms")
}

func TestPackageLockWorkspaceGraph(t *testing.T) {
	f := parseWith(t, "package-lock.json", `{
	  "lockfileVersion": 3,
	  "packages": {
	    "": {"name": "root", "dependencies": {}},
	    "packages/app": {"version": "1.0.0", "dependencies": {"lodash": "^4"}},
	    "node_modules/lodash": {"version": "4.17.21"}
	  }
	}`)
	wantRoots(t, f, "lodash")
	if _, ok := f.Packages["packages/app"]; ok {
		t.Error("workspace member path should not be recorded as a package")
	}
}

func TestPackageLockV1Graph(t *testing.T) {
	f := parseWith(t, "package-lock.json", `{
	  "lockfileVersion": 1,
	  "dependencies": {
	    "express": {"version": "4.17.1", "requires": {"debug": "^2.6.9"}},
	    "debug": {"version": "2.6.9", "requires": {"ms": "2.0.0"}},
	    "ms": {"version": "2.0.0"}
	  }
	}`)
	wantEdge(t, f, "express", "debug")
	wantEdge(t, f, "debug", "ms")
	if f.RootsKnown {
		t.Error("v1 lockfiles record no root info")
	}
}

func TestPnpmV9Graph(t *testing.T) {
	f := parseWith(t, "pnpm-lock.yaml", `lockfileVersion: '9.0'

importers:

  .:
    dependencies:
      express:
        specifier: ^4.17.1
        version: 4.17.1
    devDependencies:
      '@types/node':
        specifier: ^20.0.0
        version: 20.11.5

packages:

  '@types/node@20.11.5':
    resolution: {integrity: sha512-xxx}

  express@4.17.1:
    resolution: {integrity: sha512-yyy}

  debug@2.6.9:
    resolution: {integrity: sha512-zzz}

snapshots:

  '@types/node@20.11.5': {}

  express@4.17.1:
    dependencies:
      debug: 2.6.9

  debug@2.6.9: {}
`)
	wantRoots(t, f, "express", "@types/node")
	wantEdge(t, f, "express", "debug")
}

func TestPnpmV6Graph(t *testing.T) {
	f := parseWith(t, "pnpm-lock.yaml", `lockfileVersion: '6.0'

importers:

  .:
    dependencies:
      express:
        specifier: ^4.17.1
        version: 4.17.1

packages:

  /express@4.17.1:
    resolution: {integrity: sha512-yyy}
    dependencies:
      debug: 2.6.9

  /debug@2.6.9:
    resolution: {integrity: sha512-zzz}
`)
	wantRoots(t, f, "express")
	wantEdge(t, f, "express", "debug")
	wantPkg(t, f, "debug", "2.6.9")
}

func TestPnpmV5Graph(t *testing.T) {
	f := parseWith(t, "pnpm-lock.yaml", `lockfileVersion: 5.4

specifiers:
  express: ^4.17.1

dependencies:
  express: 4.17.1

packages:

  /express/4.17.1:
    resolution: {integrity: sha512-yyy}
    dependencies:
      debug: 2.6.9
    dev: false

  /debug/2.6.9:
    resolution: {integrity: sha512-zzz}
    dev: false
`)
	wantRoots(t, f, "express")
	wantEdge(t, f, "express", "debug")
}

func TestYarnClassicGraph(t *testing.T) {
	f := parseWith(t, "yarn.lock", `# yarn lockfile v1

express@^4.17.1:
  version "4.17.1"
  resolved "https://registry.yarnpkg.com/express/-/express-4.17.1.tgz"
  dependencies:
    debug "2.6.9"
    "@scoped/dep" "^1.0.0"

debug@2.6.9:
  version "2.6.9"

"@scoped/dep@^1.0.0":
  version "1.2.3"
`)
	wantEdge(t, f, "express", "debug")
	wantEdge(t, f, "express", "@scoped/dep")
	if f.RootsKnown {
		t.Error("yarn classic records no root info")
	}
}

func TestYarnBerryGraph(t *testing.T) {
	f := parseWith(t, "yarn.lock", `# This file is generated by running "yarn install"

__metadata:
  version: 8

"myproject@workspace:.":
  version: 0.0.0-use.local
  resolution: "myproject@workspace:."
  dependencies:
    express: "npm:^4.17.1"

"express@npm:^4.17.1":
  version: 4.17.1
  resolution: "express@npm:4.17.1"
  dependencies:
    debug: "npm:2.6.9"

"debug@npm:2.6.9":
  version: 2.6.9
`)
	wantRoots(t, f, "express")
	wantEdge(t, f, "express", "debug")
	if _, ok := f.Packages["myproject"]; ok {
		t.Error("workspace entry should not be recorded as a package")
	}
}

func TestCargoLockGraph(t *testing.T) {
	f := parseWith(t, "Cargo.lock", `version = 3

[[package]]
name = "myapp"
version = "0.1.0"
dependencies = [
 "anyhow",
 "serde 1.0.200",
]

[[package]]
name = "anyhow"
version = "1.0.86"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_derive"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
`)
	wantRoots(t, f, "anyhow", "serde")
	wantEdge(t, f, "serde", "serde_derive")
	if _, ok := f.Deps["myapp"]; ok {
		t.Error("workspace root deps should be roots, not edges")
	}
}

func TestCargoLockInlineDeps(t *testing.T) {
	f := parseWith(t, "Cargo.lock", `[[package]]
name = "app"
version = "0.1.0"
dependencies = ["libc", "bitflags 2.5.0"]

[[package]]
name = "libc"
version = "0.2.155"
source = "registry+x"

[[package]]
name = "bitflags"
version = "2.5.0"
source = "registry+x"
`)
	wantRoots(t, f, "libc", "bitflags")
}

func TestUvLockGraph(t *testing.T) {
	f := parseWith(t, "uv.lock", `version = 1

[[package]]
name = "myproj"
version = "0.1.0"
source = { editable = "." }
dependencies = [
    { name = "requests" },
]

[[package]]
name = "requests"
version = "2.32.3"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "urllib3" },
]

[[package]]
name = "urllib3"
version = "2.2.1"
source = { registry = "https://pypi.org/simple" }
`)
	wantRoots(t, f, "requests")
	wantEdge(t, f, "requests", "urllib3")
}

func TestPoetryLockGraph(t *testing.T) {
	f := parseWith(t, "poetry.lock", `[[package]]
name = "requests"
version = "2.32.3"
description = "HTTP for Humans"

[package.dependencies]
urllib3 = ">=1.21.1,<3"
certifi = ">=2017.4.17"

[package.extras]
socks = ["PySocks (>=1.5.6)"]

[[package]]
name = "urllib3"
version = "2.2.1"
description = ""

[[package]]
name = "certifi"
version = "2024.2.2"
description = ""

[metadata]
lock-version = "2.0"
`)
	wantEdge(t, f, "requests", "urllib3")
	wantEdge(t, f, "requests", "certifi")
	if f.RootsKnown {
		t.Error("poetry.lock records no root info")
	}
	if _, ok := f.Deps["requests"]; !ok {
		t.Fatal("expected deps for requests")
	}
	for _, d := range f.Deps["requests"] {
		if d == "socks" || d == "PySocks" {
			t.Error("extras must not become edges")
		}
	}
}

func TestGoModGraph(t *testing.T) {
	f := parseWith(t, "go.mod", `module example.com/m

go 1.22

require (
	github.com/direct/dep v1.2.3
	golang.org/x/sys v0.20.0 // indirect
)

require github.com/other/direct v2.0.0+incompatible
`)
	wantRoots(t, f, "github.com/direct/dep", "github.com/other/direct")
	wantPkg(t, f, "golang.org/x/sys", "0.20.0")
}

func TestComposerLockGraph(t *testing.T) {
	f := parseWith(t, "composer.lock", `{
	  "packages": [
	    {"name": "monolog/monolog", "version": "3.6.0",
	     "require": {"php": ">=8.1", "psr/log": "^2.0 || ^3.0"}}
	  ],
	  "packages-dev": [
	    {"name": "psr/log", "version": "3.0.0", "require": {"php": ">=8.0.0"}}
	  ]
	}`)
	wantEdge(t, f, "monolog/monolog", "psr/log")
	if len(f.Deps["monolog/monolog"]) != 1 {
		t.Errorf("platform requires (php) must be skipped, got %v", f.Deps["monolog/monolog"])
	}
}

func TestGemfileLockGraph(t *testing.T) {
	f := parseWith(t, "Gemfile.lock", `GEM
  remote: https://rubygems.org/
  specs:
    actionpack (7.1.3)
      rack (>= 2.2.4)
    rack (3.0.10)
    rake (13.2.1)

PLATFORMS
  ruby

DEPENDENCIES
  actionpack (~> 7.1)
  rake!

BUNDLED WITH
   2.5.9
`)
	wantRoots(t, f, "actionpack", "rake")
	wantEdge(t, f, "actionpack", "rack")
}
