package lock

import (
	"reflect"
	"testing"
)

func parseWith(t *testing.T, name string, data string) *File {
	t.Helper()
	p := ByBasename(name)
	if p == nil {
		t.Fatalf("no parser for %s", name)
	}
	f, err := p.Parse(name, []byte(data))
	if err != nil {
		t.Fatalf("parse %s: %v", name, err)
	}
	return f
}

func wantPkg(t *testing.T, f *File, name string, versions ...string) {
	t.Helper()
	if got := f.Packages[name]; !reflect.DeepEqual(got, versions) {
		t.Errorf("%s: package %q = %v, want %v", f.Kind, name, got, versions)
	}
}

func TestPackageLockV3(t *testing.T) {
	f := parseWith(t, "package-lock.json", `{
	  "lockfileVersion": 3,
	  "packages": {
	    "": {"name": "root", "version": "1.0.0"},
	    "node_modules/lodash": {"version": "4.17.21"},
	    "node_modules/@babel/core": {"version": "7.24.0"},
	    "node_modules/a/node_modules/lodash": {"version": "3.10.1"},
	    "node_modules/linked": {"link": true, "version": "1.0.0"}
	  }
	}`)
	wantPkg(t, f, "lodash", "3.10.1", "4.17.21")
	wantPkg(t, f, "@babel/core", "7.24.0")
	if _, ok := f.Packages["linked"]; ok {
		t.Error("link entries should be skipped")
	}
}

func TestPackageLockV1(t *testing.T) {
	f := parseWith(t, "package-lock.json", `{
	  "lockfileVersion": 1,
	  "dependencies": {
	    "express": {"version": "4.17.1", "dependencies": {
	      "debug": {"version": "2.6.9"}
	    }}
	  }
	}`)
	wantPkg(t, f, "express", "4.17.1")
	wantPkg(t, f, "debug", "2.6.9")
}

func TestPnpmLockV9(t *testing.T) {
	f := parseWith(t, "pnpm-lock.yaml", `lockfileVersion: '9.0'

importers:
  .:
    dependencies:
      chalk:
        specifier: 5.3.0
        version: 5.3.0

packages:

  '@scope/pkg@2.1.0':
    resolution: {integrity: sha512-x}

  chalk@5.3.0:
    resolution: {integrity: sha512-y}

  peered@1.0.0(react@18.2.0):
    resolution: {integrity: sha512-z}

snapshots:

  chalk@5.3.0: {}
`)
	wantPkg(t, f, "chalk", "5.3.0")
	wantPkg(t, f, "@scope/pkg", "2.1.0")
	wantPkg(t, f, "peered", "1.0.0")
}

func TestPnpmLockV6(t *testing.T) {
	f := parseWith(t, "pnpm-lock.yaml", `lockfileVersion: '6.0'

packages:

  /@types/node@20.1.0:
    resolution: {integrity: sha512-x}
    dev: true

  /is-odd@3.0.1:
    resolution: {integrity: sha512-y}
`)
	wantPkg(t, f, "@types/node", "20.1.0")
	wantPkg(t, f, "is-odd", "3.0.1")
}

func TestYarnClassic(t *testing.T) {
	f := parseWith(t, "yarn.lock", `# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.22.13":
  version "7.23.5"
  resolved "https://registry.yarnpkg.com/..."

is-number@^7.0.0:
  version "7.0.0"
`)
	wantPkg(t, f, "@babel/code-frame", "7.23.5")
	wantPkg(t, f, "is-number", "7.0.0")
}

func TestYarnBerry(t *testing.T) {
	f := parseWith(t, "yarn.lock", `__metadata:
  version: 8

"chalk@npm:^5.0.0":
  version: 5.3.0
  resolution: "chalk@npm:5.3.0"

"@scope/thing@npm:1.0.0, @scope/thing@npm:^1.0.0":
  version: 1.0.0
`)
	wantPkg(t, f, "chalk", "5.3.0")
	wantPkg(t, f, "@scope/thing", "1.0.0")
}

func TestBunLock(t *testing.T) {
	f := parseWith(t, "bun.lock", `{
  "lockfileVersion": 1,
  "packages": {
    "lodash": ["lodash@4.17.21", "", {}, "sha512-x"],
    "@types/react": ["@types/react@18.2.0", "", {}, "sha512-y"],
  }
}`)
	wantPkg(t, f, "lodash", "4.17.21")
	wantPkg(t, f, "@types/react", "18.2.0")
}

func TestCargoLock(t *testing.T) {
	f := parseWith(t, "Cargo.lock", `version = 3

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "serde"
version = "0.9.15"

[metadata]
"checksum foo" = "bar"
`)
	wantPkg(t, f, "serde", "0.9.15", "1.0.200")
}

func TestUvLock(t *testing.T) {
	f := parseWith(t, "uv.lock", `version = 1

[[package]]
name = "requests"
version = "2.32.3"
source = { registry = "https://pypi.org/simple" }

[package.metadata]
requires-dist = []

[[package]]
name = "urllib3"
version = "2.2.1"
`)
	wantPkg(t, f, "requests", "2.32.3")
	wantPkg(t, f, "urllib3", "2.2.1")
}

func TestRequirementsTxt(t *testing.T) {
	f := parseWith(t, "requirements.txt", `# comment
Django==5.0.0
requests[security]==2.31.0  # inline comment ok
pillow==10.0.0 ; python_version > "3.8"
-r base.txt
not-pinned>=1.0
My_Package.Name==1.2.3
`)
	wantPkg(t, f, "django", "5.0.0")
	wantPkg(t, f, "requests", "2.31.0")
	wantPkg(t, f, "pillow", "10.0.0")
	wantPkg(t, f, "my-package-name", "1.2.3")
	if _, ok := f.Packages["not-pinned"]; ok {
		t.Error("range requirements must be skipped")
	}
}

func TestGoMod(t *testing.T) {
	f := parseWith(t, "go.mod", `module example.com/app

go 1.22

require (
	github.com/gorilla/mux v1.8.1
	golang.org/x/text v0.14.0 // indirect
)

require github.com/stretchr/testify v1.9.0

replace github.com/gorilla/mux => ../local
`)
	wantPkg(t, f, "github.com/gorilla/mux", "1.8.1")
	wantPkg(t, f, "golang.org/x/text", "0.14.0")
	wantPkg(t, f, "github.com/stretchr/testify", "1.9.0")
}

func TestComposerLock(t *testing.T) {
	f := parseWith(t, "composer.lock", `{
	  "packages": [{"name": "monolog/monolog", "version": "3.5.0"}],
	  "packages-dev": [{"name": "phpunit/phpunit", "version": "v10.5.0"}]
	}`)
	wantPkg(t, f, "monolog/monolog", "3.5.0")
	wantPkg(t, f, "phpunit/phpunit", "10.5.0")
}

func TestGemfileLock(t *testing.T) {
	f := parseWith(t, "Gemfile.lock", `GEM
  remote: https://rubygems.org/
  specs:
    rack (3.0.0)
    rails (7.1.0)
      actionpack (= 7.1.0)

PLATFORMS
  ruby

DEPENDENCIES
  rails
`)
	wantPkg(t, f, "rack", "3.0.0")
	wantPkg(t, f, "rails", "7.1.0")
	if _, ok := f.Packages["actionpack"]; ok {
		t.Error("dependency constraint lines must be skipped")
	}
}

func TestGemfileLockNonRegistrySources(t *testing.T) {
	f := parseWith(t, "Gemfile.lock", `GIT
  remote: https://github.com/someone/fork.git
  revision: abc123
  specs:
    patched-gem (9.9.9)

PATH
  remote: engines/local
  specs:
    local-engine (0.1.0)

GEM
  remote: https://rubygems.org/
  specs:
    rack (3.0.0)

DEPENDENCIES
  local-engine!
  patched-gem!
  rack
`)
	wantPkg(t, f, "patched-gem", "9.9.9")
	wantPkg(t, f, "local-engine", "0.1.0")
	wantPkg(t, f, "rack", "3.0.0")
	if !f.NonRegistry["patched-gem"] {
		t.Error("GIT-sourced gems must be marked non-registry")
	}
	if !f.NonRegistry["local-engine"] {
		t.Error("PATH-sourced gems must be marked non-registry")
	}
	if f.NonRegistry["rack"] {
		t.Error("GEM-sourced gems must not be marked non-registry")
	}
}

func TestGoModReplaceNonRegistry(t *testing.T) {
	f := parseWith(t, "go.mod", `module example.com/app

require (
	github.com/grafana/grafana/pkg/apimachinery v0.0.0
	github.com/pkg/errors v0.9.1
)

require github.com/acme/single v1.2.3

replace github.com/acme/single => ../single

replace (
	github.com/grafana/grafana/pkg/apimachinery => ../../pkg/apimachinery
	github.com/other/mod v1.0.0 => github.com/fork/mod v1.0.1
)
`)
	for _, name := range []string{"github.com/grafana/grafana/pkg/apimachinery", "github.com/acme/single", "github.com/other/mod"} {
		if !f.NonRegistry[name] {
			t.Errorf("%s: replaced module not marked NonRegistry", name)
		}
	}
	if f.NonRegistry["github.com/pkg/errors"] {
		t.Error("github.com/pkg/errors wrongly marked NonRegistry")
	}
	if len(f.Packages["github.com/pkg/errors"]) == 0 || len(f.Packages["github.com/acme/single"]) == 0 {
		t.Error("require entries missing from Packages")
	}
}

func TestYarnNpmAliasNonRegistry(t *testing.T) {
	f := parseWith(t, "yarn.lock", `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8

"wrap-ansi-cjs@npm:wrap-ansi@^7.0.0":
  version: 7.0.0
  resolution: "wrap-ansi@npm:7.0.0"

"chalk@npm:^5.0.0":
  version: 5.3.0
  resolution: "chalk@npm:5.3.0"

"@scoped/alias@npm:@real/pkg@^1.0.0":
  version: 1.4.0
  resolution: "@real/pkg@npm:1.4.0"
`)
	if !f.NonRegistry["wrap-ansi-cjs"] {
		t.Error("wrap-ansi-cjs alias not marked NonRegistry")
	}
	if !f.NonRegistry["@scoped/alias"] {
		t.Error("@scoped/alias not marked NonRegistry")
	}
	if f.NonRegistry["chalk"] {
		t.Error("chalk (plain npm: range, no alias) wrongly marked NonRegistry")
	}
	if len(f.Packages["wrap-ansi-cjs"]) == 0 || len(f.Packages["chalk"]) == 0 {
		t.Error("yarn entries missing from Packages")
	}
}
