package lock

import (
	"reflect"
	"testing"
)

func mustParse(t *testing.T, basename string, data string) *File {
	t.Helper()
	p := ByBasename(basename)
	if p == nil {
		t.Fatalf("no parser for %s", basename)
	}
	f, err := p.Parse(basename, []byte(data))
	if err != nil {
		t.Fatalf("parse %s: %v", basename, err)
	}
	return f
}

func wantPkgs(t *testing.T, f *File, want map[string][]string) {
	t.Helper()
	if !reflect.DeepEqual(f.Packages, want) {
		t.Errorf("packages mismatch\n got: %v\nwant: %v", f.Packages, want)
	}
}

func TestPipfileLock(t *testing.T) {
	f := mustParse(t, "Pipfile.lock", `{
	"_meta": {"hash": {"sha256": "abc"}, "pipfile-spec": 6},
	"default": {
		"requests": {"hashes": ["sha256:x"], "version": "==2.31.0"},
		"Django": {"version": "==5.0.1"}
	},
	"develop": {
		"pytest": {"version": "==8.0.0"}
	}
}`)
	if f.Ecosystem != PyPI {
		t.Errorf("ecosystem = %s", f.Ecosystem)
	}
	wantPkgs(t, f, map[string][]string{
		"requests": {"2.31.0"}, "django": {"5.0.1"}, "pytest": {"8.0.0"},
	})
}

func TestMixLock(t *testing.T) {
	f := mustParse(t, "mix.lock", `%{
  "phoenix": {:hex, :phoenix, "1.7.10", "cffd", [:mix], [{:castore, ">= 0.0.0", [hex: :castore]}], "hexpm", "aaa"},
  "plug": {:hex, :plug, "1.15.2", "bbb", [:mix], [], "hexpm", "ccc"},
  "my_git_dep": {:git, "https://github.com/x/y.git", "deadbeef", []},
  "acme_core": {:hex, :acme_core, "0.3.1", "ddd", [:mix], [{:plug, "~> 1.0", [hex: :plug, repo: "hexpm"]}], "acme", "eee"},
  "chatterbox": {:hex, :ts_chatterbox, "0.16.0", "fff", [:rebar3], [], "hexpm", "ggg"},
}
`)
	if f.Ecosystem != Hex {
		t.Errorf("ecosystem = %s", f.Ecosystem)
	}
	wantPkgs(t, f, map[string][]string{
		// ts_chatterbox: the Hex package name (after :hex), not the OTP
		// app name keying the map, is what registries and OSV know.
		"phoenix": {"1.7.10"}, "plug": {"1.15.2"}, "acme_core": {"0.3.1"},
		"ts_chatterbox": {"0.16.0"},
	})
	if !f.NonRegistry["acme_core"] {
		t.Errorf("acme_core (private hex repo) should be NonRegistry")
	}
	if f.NonRegistry["phoenix"] || f.NonRegistry["plug"] {
		t.Errorf("hexpm entries must stay registry: %v", f.NonRegistry)
	}
}

func TestPubspecLock(t *testing.T) {
	f := mustParse(t, "pubspec.lock", `# Generated by pub
packages:
  args:
    dependency: transitive
    description:
      name: args
      sha256: "eef6c46b622e0494a36c5a12d10d77fb4e855501a91c1b9ef9339326e58f0596"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.2"
  http:
    dependency: "direct main"
    source: hosted
    version: 1.2.0
sdks:
  dart: ">=3.2.0 <4.0.0"
`)
	if f.Ecosystem != Pub {
		t.Errorf("ecosystem = %s", f.Ecosystem)
	}
	wantPkgs(t, f, map[string][]string{
		"args": {"2.4.2"}, "http": {"1.2.0"},
	})
}

func TestGradleLockfile(t *testing.T) {
	f := mustParse(t, "gradle.lockfile", `# This is a Gradle generated file for dependency locking.
# Manual edits can break the build and are not advised.
# This file is expected to be part of source control.
com.fasterxml.jackson.core:jackson-databind:2.16.1=compileClasspath,runtimeClasspath
org.slf4j:slf4j-api:2.0.11=compileClasspath
empty=annotationProcessor
`)
	if f.Ecosystem != Maven {
		t.Errorf("ecosystem = %s", f.Ecosystem)
	}
	wantPkgs(t, f, map[string][]string{
		"com.fasterxml.jackson.core:jackson-databind": {"2.16.1"},
		"org.slf4j:slf4j-api":                         {"2.0.11"},
	})
}

func TestNuGetLock(t *testing.T) {
	f := mustParse(t, "packages.lock.json", `{
	"version": 1,
	"dependencies": {
		"net6.0": {
			"Newtonsoft.Json": {"type": "Direct", "requested": "[13.0.1, )", "resolved": "13.0.1", "contentHash": "x"},
			"System.Buffers": {"type": "Transitive", "resolved": "4.5.1"},
			"MyLocalProject": {"type": "Project"}
		},
		"net6.0/win-x64": {
			"Newtonsoft.Json": {"type": "Direct", "resolved": "13.0.1"}
		}
	}
}`)
	if f.Ecosystem != NuGet {
		t.Errorf("ecosystem = %s", f.Ecosystem)
	}
	wantPkgs(t, f, map[string][]string{
		"Newtonsoft.Json": {"13.0.1"}, "System.Buffers": {"4.5.1"},
	})
}

func TestSwiftResolvedV2(t *testing.T) {
	f := mustParse(t, "Package.resolved", `{
	"pins": [
		{
			"identity": "swift-argument-parser",
			"kind": "remoteSourceControl",
			"location": "https://github.com/apple/swift-argument-parser.git",
			"state": {"revision": "abc", "version": "1.3.0"}
		},
		{
			"identity": "local-only",
			"kind": "remoteSourceControl",
			"location": "https://github.com/x/branch-dep",
			"state": {"branch": "main", "revision": "def"}
		}
	],
	"version": 2
}`)
	if f.Ecosystem != SwiftURL {
		t.Errorf("ecosystem = %s", f.Ecosystem)
	}
	wantPkgs(t, f, map[string][]string{
		"github.com/apple/swift-argument-parser": {"1.3.0"},
	})
}

func TestSwiftResolvedV1(t *testing.T) {
	f := mustParse(t, "Package.resolved", `{
	"object": {
		"pins": [
			{
				"package": "SwiftNIO",
				"repositoryURL": "https://github.com/apple/swift-nio.git",
				"state": {"branch": null, "revision": "abc", "version": "2.62.0"}
			}
		]
	},
	"version": 1
}`)
	wantPkgs(t, f, map[string][]string{
		"github.com/apple/swift-nio": {"2.62.0"},
	})
}

func TestSwiftURLName(t *testing.T) {
	cases := map[string]string{
		"https://github.com/apple/swift-nio.git": "github.com/apple/swift-nio",
		"git@github.com:apple/swift-nio.git":     "github.com/apple/swift-nio",
		"ssh://git@github.com/apple/swift-nio":   "github.com/apple/swift-nio",
	}
	for in, want := range cases {
		if got := swiftURLName(in); got != want {
			t.Errorf("swiftURLName(%q) = %q, want %q", in, got, want)
		}
	}
}
