package lock

import (
	"reflect"
	"sort"
	"testing"
)

const juliaManifestV2 = `# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.1"
manifest_format = "2.0"
project_hash = "9a2bce32843f4e3f7471a5c7b7d89536ee741f6e"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
version = "1.11.0"

[[deps.CodecZlib]]
deps = ["TranscodingStreams", "Zlib_jll"]
git-tree-sha1 = "962834c22b66e32aa10f7611c08c8ca4e20749a9"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.7.8"

[[deps.Adapt]]
deps = ["Artifacts"]
git-tree-sha1 = "50c3c56a52972d78e8be9fd135bfb91c9574c140"
uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
version = "4.1.1"
weakdeps = ["StaticArrays"]

    [deps.Adapt.extensions]
    AdaptStaticArraysExt = "StaticArrays"

[[deps.TranscodingStreams]]
git-tree-sha1 = "0c45878dcfdcfa8480052b6ab162cdd138781742"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.11.3"

[[deps.Zlib_jll]]
deps = ["Artifacts"]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.3.1+1"
`

func TestJuliaManifestV2(t *testing.T) {
	f, err := parseJuliaManifest("Manifest.toml", []byte(juliaManifestV2))
	if err != nil {
		t.Fatal(err)
	}
	want := map[string][]string{
		"Artifacts":          {"1.11.0"},
		"CodecZlib":          {"0.7.8"},
		"Adapt":              {"4.1.1"},
		"TranscodingStreams": {"0.11.3"},
		"Zlib_jll":           {"1.3.1+1"},
	}
	if !reflect.DeepEqual(f.Packages, want) {
		t.Errorf("packages = %v", f.Packages)
	}
	deps := f.Deps["CodecZlib"]
	sort.Strings(deps)
	if !reflect.DeepEqual(deps, []string{"TranscodingStreams", "Zlib_jll"}) {
		t.Errorf("CodecZlib deps = %v", deps)
	}
	// weakdeps and extensions sub-tables must not pollute the graph.
	for _, d := range f.Deps["Adapt"] {
		if d == "StaticArrays" || d == "AdaptStaticArraysExt" {
			t.Errorf("Adapt gained weakdep edge %q", d)
		}
	}
	if f.RootsKnown {
		t.Error("roots should be unknown (they live in Project.toml)")
	}
	if f.Ecosystem != Julia {
		t.Errorf("eco = %s", f.Ecosystem)
	}
}

const juliaManifestV1 = `# This file is machine-generated - editing it directly is not advised

[[AbstractFFTs]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "051c95d6836228d120f5f4b984dd5aba1624f716"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.5.0"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
`

func TestJuliaManifestV1(t *testing.T) {
	f, err := parseJuliaManifest("Manifest.toml", []byte(juliaManifestV1))
	if err != nil {
		t.Fatal(err)
	}
	if got := f.Packages["AbstractFFTs"]; !reflect.DeepEqual(got, []string{"0.5.0"}) {
		t.Errorf("AbstractFFTs = %v", got)
	}
	// Old-format stdlibs carry no version and are dropped, along with
	// edges pointing at them.
	if _, ok := f.Packages["LinearAlgebra"]; ok {
		t.Error("versionless stdlib should be dropped")
	}
	if len(f.Deps["AbstractFFTs"]) != 0 {
		t.Errorf("edges to unlocked packages kept: %v", f.Deps["AbstractFFTs"])
	}
}

const stackLock = `# This file was autogenerated by Stack.
packages:
- completed:
    hackage: crypton-1.1.4@sha256:500174e81f6ad6b4c23a4e773771b934834ab3b953ef544cc6163eb952196c64,15142
    pantry-tree:
      sha256: 5c3b08f14c438643625daf0eb5eb079c3aefc563d55d2886de1683c78ddcc2da
      size: 23413
  original:
    hackage: crypton-1.1.4@sha256:500174e81f6ad6b4c23a4e773771b934834ab3b953ef544cc6163eb952196c64,15142
- completed:
    hackage: unordered-containers-0.2.19.1@sha256:aa,1234
  original:
    hackage: unordered-containers-0.2.19.1
- completed:
    commit: abc123
    git: https://github.com/example/repo
  original:
    git: https://github.com/example/repo
snapshots:
- completed:
    sha256: 5a59b2a405b3aba3c00188453be172b85893cab8ebc352b1ef58b0eae5d248a2
    size: 650475
    url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/24/16.yaml
  original: lts-24.16
`

func TestStackYamlLock(t *testing.T) {
	f, err := parseStackYamlLock("stack.yaml.lock", []byte(stackLock))
	if err != nil {
		t.Fatal(err)
	}
	want := map[string][]string{
		"crypton":              {"1.1.4"},
		"unordered-containers": {"0.2.19.1"},
	}
	if !reflect.DeepEqual(f.Packages, want) {
		t.Errorf("packages = %v", f.Packages)
	}
	if f.Ecosystem != Hackage {
		t.Errorf("eco = %s", f.Ecosystem)
	}
}

const cabalFreeze = `active-repositories: hackage.haskell.org:merge
constraints: any.Cabal ==3.10.3.0,
             any.aeson ==2.2.3.0,
             aeson +ordered-keymap,
             any.text -simdutf,
             any.base ==4.19.2.0,
             any.rts installed
index-state: hackage.haskell.org 2026-01-01T00:00:00Z
`

const stackageCabalConfig = `-- Please place this file next to your .cabal file as cabal.config
-- To only use tested packages, uncomment the following line:
constraints: abstract-deque ==0.3,
             AC-Angle ==1.0,
             base64-bytestring ==1.2.1.0
`

func TestCabalFreeze(t *testing.T) {
	f, err := parseCabalFreeze("cabal.project.freeze", []byte(cabalFreeze))
	if err != nil {
		t.Fatal(err)
	}
	want := map[string][]string{
		"Cabal": {"3.10.3.0"},
		"aeson": {"2.2.3.0"},
		"text":  {},
		"base":  {"4.19.2.0"},
	}
	delete(want, "text") // flag constraint, no version
	if !reflect.DeepEqual(f.Packages, want) {
		t.Errorf("packages = %v", f.Packages)
	}

	f2, err := parseCabalFreeze("cabal.config", []byte(stackageCabalConfig))
	if err != nil {
		t.Fatal(err)
	}
	if got := f2.Packages["base64-bytestring"]; !reflect.DeepEqual(got, []string{"1.2.1.0"}) {
		t.Errorf("base64-bytestring = %v (all: %v)", got, f2.Packages)
	}
	if got := f2.Packages["AC-Angle"]; !reflect.DeepEqual(got, []string{"1.0"}) {
		t.Errorf("AC-Angle = %v", got)
	}
}

const gleamManifest = `# This file was generated by Gleam
# You typically do not need to edit this file

packages = [
  { name = "argv", version = "1.0.2", build_tools = ["gleam"], requirements = [], otp_app = "argv", source = "hex", outer_checksum = "BA1FF0929525DEBA1CE67256E5ADF77A7CDDFE729E3E3F57A5BDCAA031DED09D" },
  { name = "gleam_stdlib", version = "0.60.0", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "F5A6A97E278F9EF2C222BE6E56D74B90F6F3A1C7A22C4F162E7E1F76BEE3931A" },
  { name = "simplifile", version = "2.2.1", build_tools = ["gleam"], requirements = ["filepath", "gleam_stdlib"], otp_app = "simplifile", source = "hex", outer_checksum = "6A868D5D0FD7C7A22C4F162E7E1F76BEE3931AF5A6A97E278F9EF2C222BE6E56" },
  { name = "filepath", version = "1.1.2", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "filepath", source = "hex", outer_checksum = "31F1BFDF9DA119EABC0B48926BB74F2ECFD7EE9E94AA6C7A22C4F162E7E1F76B" },
]

[requirements]
argv = { version = ">= 1.0.0 and < 2.0.0" }
gleam_stdlib = { version = ">= 0.44.0 and < 2.0.0" }
simplifile = { version = ">= 2.0.0 and < 3.0.0" }
`

func TestGleamManifest(t *testing.T) {
	f, err := parseGleamManifest("manifest.toml", []byte(gleamManifest))
	if err != nil {
		t.Fatal(err)
	}
	if got := f.Packages["simplifile"]; !reflect.DeepEqual(got, []string{"2.2.1"}) {
		t.Errorf("simplifile = %v", got)
	}
	if len(f.Packages) != 4 {
		t.Errorf("want 4 packages, got %v", f.Packages)
	}
	deps := f.Deps["simplifile"]
	sort.Strings(deps)
	if !reflect.DeepEqual(deps, []string{"filepath", "gleam_stdlib"}) {
		t.Errorf("simplifile deps = %v", deps)
	}
	if !f.RootsKnown {
		t.Fatal("roots should be known")
	}
	roots := append([]string(nil), f.Roots...)
	sort.Strings(roots)
	if !reflect.DeepEqual(roots, []string{"argv", "gleam_stdlib", "simplifile"}) {
		t.Errorf("roots = %v", roots)
	}
	if f.Ecosystem != Hex {
		t.Errorf("eco = %s", f.Ecosystem)
	}
}

func TestManifestTOMLSniff(t *testing.T) {
	// Uppercase basename routes to Julia, lowercase to Gleam, but content
	// wins when it is unambiguous.
	p := ByBasename("Manifest.toml")
	f, err := p.Parse("Manifest.toml", []byte(gleamManifest))
	if err != nil {
		t.Fatal(err)
	}
	if f.Ecosystem != Hex {
		t.Errorf("gleam content under uppercase name: eco = %s", f.Ecosystem)
	}
	p = ByBasename("manifest.toml")
	f, err = p.Parse("manifest.toml", []byte(juliaManifestV2))
	if err != nil {
		t.Fatal(err)
	}
	if f.Ecosystem != Julia {
		t.Errorf("julia content under lowercase name: eco = %s", f.Ecosystem)
	}
	if ByBasename("Manifest-v1.11.toml") == nil {
		t.Error("versioned Julia manifest not recognized")
	}
	if ByBasename("stack.yaml.lock") == nil || ByBasename("cabal.project.freeze") == nil || ByBasename("cabal.config") == nil {
		t.Error("haskell basenames not recognized")
	}
}

// TestNonRegistryMarks: packages a lockfile says are not from the public
// registry (workspace members, git/path deps, poetry source tables) must be
// marked so registry-metadata checks skip them.
func TestNonRegistryMarks(t *testing.T) {
	cargo := `[[package]]
name = "my-workspace-crate"
version = "25.7.0"
dependencies = ["serde"]

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "forked-thing"
version = "2.0.0"
source = "git+https://github.com/me/forked-thing?rev=abc123"
`
	f := parseWith(t, "Cargo.lock", cargo)
	if !f.NonRegistry["my-workspace-crate"] {
		t.Error("Cargo workspace member (no source) must be NonRegistry")
	}
	if !f.NonRegistry["forked-thing"] {
		t.Error("Cargo git dependency must be NonRegistry")
	}
	if f.NonRegistry["serde"] {
		t.Error("registry crate must NOT be NonRegistry")
	}

	poetry := `[[package]]
name = "requests"
version = "2.32.0"

[[package]]
name = "internal-tool"
version = "1.0.0"

[package.source]
type = "git"
url = "https://github.com/corp/internal-tool"
`
	f = parseWith(t, "poetry.lock", poetry)
	if !f.NonRegistry["internal-tool"] {
		t.Error("poetry package with a source table must be NonRegistry")
	}
	if f.NonRegistry["requests"] {
		t.Error("plain poetry package must NOT be NonRegistry")
	}

	npm := `{
  "lockfileVersion": 3,
  "packages": {
    "": {"dependencies": {"a": "^1.0.0"}},
    "node_modules/a": {"version": "1.0.0", "resolved": "https://registry.npmjs.org/a/-/a-1.0.0.tgz"},
    "node_modules/b": {"version": "2.0.0", "resolved": "git+ssh://git@github.com/me/b.git#abc"},
    "node_modules/c": {"version": "3.0.0", "resolved": "file:../c"}
  }
}`
	f = parseWith(t, "package-lock.json", npm)
	if f.NonRegistry["a"] {
		t.Error("npm registry package must NOT be NonRegistry")
	}
	if !f.NonRegistry["b"] || !f.NonRegistry["c"] {
		t.Errorf("npm git/file deps must be NonRegistry, got %v", f.NonRegistry)
	}
}
