package lock

import (
	"strings"
	"testing"
)

const pdmLock = `# This file is @generated by PDM.
# It is not intended for manual editing.

[metadata]
groups = ["default", "test"]
strategy = ["inherit_metadata"]
lock_version = "4.5.1"
content_hash = "sha256:c3f6d458b99d53437990fe3a5789d402dba4b471df42276a1492a80baf130777"

[[metadata.targets]]
requires_python = ">=3.10"

[[package]]
name = "anyio"
version = "4.13.0"
requires_python = ">=3.10"
summary = "High-level concurrency and networking framework"
groups = ["default", "test"]
dependencies = [
    "exceptiongroup>=1.0.2; python_version < \"3.11\"",
    "idna>=2.8",
    "typing-extensions>=4.5; python_version < \"3.13\"",
]
files = [
    {file = "anyio-4.13.0-py3-none-any.whl", hash = "sha256:08b310f9e24a9594186fd75b4f73f4a4152069e3853f1ed8bfbf58369f4ad708"},
    {file = "anyio-4.13.0.tar.gz", hash = "sha256:334b70e641fd2221c1505b3890c69882fe4a2df910cba14d97019b90b24439dc"},
]

[[package]]
name = "idna"
version = "3.10"
requires_python = ">=3.6"
summary = "IDNA support"
groups = ["default", "test"]
files = [
    {file = "idna-3.10-py3-none-any.whl", hash = "sha256:946d195a0d259cbba61165e88e65941f16e9b36ea6ddb97f00452bae8b1287d3"},
]

[[package]]
name = "demo-git"
version = "0.0.1"
git = "https://github.com/example/demo.git"
ref = "main"
revision = "1234567890abcdef1234567890abcdef12345678"
summary = "a git dep"
groups = ["default"]

[[package]]
name = "demo-local"
version = "0.2.0"
path = "./pkgs/demo-local"
summary = "a local dep"
groups = ["default"]

[[package]]
name = "requests"
version = "2.31.0"
extras = ["socks"]
requires_python = ">=3.7"
summary = "extras entry"
groups = ["default"]
dependencies = [
    "pysocks!=1.5.7,>=1.5.6",
    "requests==2.31.0",
]
files = [
    {file = "requests-2.31.0-py3-none-any.whl", hash = "sha256:58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f"},
]
`

func TestParsePDMLock(t *testing.T) {
	p := ByBasename("pdm.lock")
	if p == nil {
		t.Fatal("no parser for pdm.lock")
	}
	f, err := p.Parse("pdm.lock", []byte(pdmLock))
	if err != nil {
		t.Fatal(err)
	}
	if got := f.Packages["anyio"]; len(got) != 1 || got[0] != "4.13.0" {
		t.Fatalf("anyio = %v", got)
	}
	if got := f.Packages["idna"]; len(got) != 1 || got[0] != "3.10" {
		t.Fatalf("idna = %v", got)
	}
	// files hashes become integrity pins (both artifacts joined).
	pin := f.Pin("anyio", "4.13.0").Integrity
	if !strings.Contains(pin, "08b310f9e24a9594186fd75b4f73f4a4152069e3853f1ed8bfbf58369f4ad708") ||
		!strings.Contains(pin, "334b70e641fd2221c1505b3890c69882fe4a2df910cba14d97019b90b24439dc") {
		t.Fatalf("anyio pin = %q", pin)
	}
	// the lock-wide content_hash must NOT leak into any pin.
	for name, vs := range f.Packages {
		for _, v := range vs {
			if strings.Contains(f.Pin(name, v).Integrity, "c3f6d458b99d53437") {
				t.Fatalf("content_hash leaked into pin for %s", name)
			}
		}
	}
	// PEP 508 dep strings: name is the leading run, markers/specifiers cut.
	deps := f.Deps["anyio"]
	want := map[string]bool{"exceptiongroup": true, "idna": true, "typing-extensions": true}
	for _, d := range deps {
		if !want[d] {
			t.Fatalf("unexpected anyio dep %q", d)
		}
		delete(want, d)
	}
	if len(want) != 0 {
		t.Fatalf("missing anyio deps: %v", want)
	}
	// git and path candidates never get registry claims.
	if !f.NonRegistry["demo-git"] {
		t.Fatal("git dep not marked NonRegistry")
	}
	if !f.NonRegistry["demo-local"] {
		t.Fatal("path dep not marked NonRegistry")
	}
	if f.NonRegistry["anyio"] || f.NonRegistry["requests"] {
		t.Fatal("registry package wrongly marked NonRegistry")
	}
	// extras entry parses under its base name.
	if got := f.Packages["requests"]; len(got) != 1 || got[0] != "2.31.0" {
		t.Fatalf("requests = %v", got)
	}
}
