package lock

import "testing"

func wantPin(t *testing.T, f *File, name, ver, integ, host string) {
	t.Helper()
	pm := f.Pin(name, ver)
	if pm.Integrity != integ || pm.Host != host {
		t.Fatalf("%s@%s pin = %+v, want integrity=%q host=%q", name, ver, pm, integ, host)
	}
}

func TestYarnClassicPins(t *testing.T) {
	f := mustParse(t, "yarn.lock", `# yarn lockfile v1

left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz#5b8a3a7765dfe001261dde915589e782f8c94d1e"
  integrity sha512-XI5MPzVNApjAyhQzphX8BkmKsKUxD4LdyK24iZeQGinBN9yTQT3bFlCBy/aVx2HrNcqQGsdot8ghrjyrvMCoEA==
`)
	wantPin(t, f, "left-pad", "1.3.0",
		"5b8a3a7765dfe001261dde915589e782f8c94d1e sha512-XI5MPzVNApjAyhQzphX8BkmKsKUxD4LdyK24iZeQGinBN9yTQT3bFlCBy/aVx2HrNcqQGsdot8ghrjyrvMCoEA==",
		"registry.yarnpkg.com")
}

func TestYarnBerryPins(t *testing.T) {
	f := mustParse(t, "yarn.lock", `# This file is generated by running "yarn install"

"left-pad@npm:^1.3.0":
  version: 1.3.0
  resolution: "left-pad@npm:1.3.0"
  checksum: 10c0/da3a1f60e3993295a03dae4bd4c6b0eae2d5b3f2
  languageName: node
  linkType: hard
`)
	wantPin(t, f, "left-pad", "1.3.0", "10c0/da3a1f60e3993295a03dae4bd4c6b0eae2d5b3f2", "")
}

func TestPnpmPins(t *testing.T) {
	f := mustParse(t, "pnpm-lock.yaml", `lockfileVersion: '9.0'

packages:

  left-pad@1.3.0:
    resolution: {integrity: sha512-XI5MPzVNApjAyhQzphX8Bkm}

  private-pkg@2.0.0:
    resolution: {integrity: sha512-abc, tarball: https://npm.corp.internal/private-pkg/-/private-pkg-2.0.0.tgz}
`)
	wantPin(t, f, "left-pad", "1.3.0", "sha512-XI5MPzVNApjAyhQzphX8Bkm", "")
	wantPin(t, f, "private-pkg", "2.0.0", "sha512-abc", "npm.corp.internal")
}

func TestCargoPins(t *testing.T) {
	f := mustParse(t, "Cargo.lock", `version = 3

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "ddc6f9cc94d67c0e21aaf7eda3a010fd3af78ebf6e096aa6e2e13c79749cce4f"

[[package]]
name = "internal-crate"
version = "0.1.0"
source = "sparse+https://crates.corp.internal/index/"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"
`)
	wantPin(t, f, "serde", "1.0.200",
		"ddc6f9cc94d67c0e21aaf7eda3a010fd3af78ebf6e096aa6e2e13c79749cce4f", "crates.io")
	wantPin(t, f, "internal-crate", "0.1.0",
		"1111111111111111111111111111111111111111111111111111111111111111", "crates.corp.internal")
}

func TestPoetryPins(t *testing.T) {
	f := mustParse(t, "poetry.lock", `[[package]]
name = "requests"
version = "2.32.0"
description = "HTTP for Humans"
files = [
    {file = "requests-2.32.0-py3-none-any.whl", hash = "sha256:aaaa"},
    {file = "requests-2.32.0.tar.gz", hash = "sha256:bbbb"},
]

[[package]]
name = "internal-lib"
version = "1.0.0"
files = [
    {file = "internal_lib-1.0.0.tar.gz", hash = "sha256:cccc"},
]

[package.source]
type = "legacy"
url = "https://pypi.corp.internal/simple"
reference = "corp"

[metadata]
content-hash = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
`)
	wantPin(t, f, "requests", "2.32.0", "sha256:aaaa sha256:bbbb", "pypi.org")
	wantPin(t, f, "internal-lib", "1.0.0", "sha256:cccc", "pypi.corp.internal")
}

func TestUvPins(t *testing.T) {
	f := mustParse(t, "uv.lock", `version = 1

[[package]]
name = "idna"
version = "3.7"
source = { registry = "https://pypi.org/simple" }
sdist = { url = "https://files.pythonhosted.org/packages/idna-3.7.tar.gz", hash = "sha256:dddd", size = 1 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/idna-3.7-py3-none-any.whl", hash = "sha256:eeee", size = 2 },
]
`)
	wantPin(t, f, "idna", "3.7", "sha256:dddd sha256:eeee", "pypi.org")
}

func TestPipfilePins(t *testing.T) {
	f := mustParse(t, "Pipfile.lock", `{
  "_meta": {"sources": [
    {"name": "pypi", "url": "https://pypi.org/simple", "verify_ssl": true},
    {"name": "corp", "url": "https://pypi.corp.internal/simple", "verify_ssl": true}
  ]},
  "default": {
    "requests": {"version": "==2.32.0", "hashes": ["sha256:aaaa", "sha256:bbbb"], "index": "pypi"},
    "internal-lib": {"version": "==1.0.0", "hashes": ["sha256:cccc"], "index": "corp"}
  }
}`)
	wantPin(t, f, "requests", "2.32.0", "sha256:aaaa sha256:bbbb", "pypi.org")
	wantPin(t, f, "internal-lib", "1.0.0", "sha256:cccc", "pypi.corp.internal")
}

func TestRequirementsHashPins(t *testing.T) {
	f := mustParse(t, "requirements.txt", `requests==2.32.0 \
    --hash=sha256:aaaa \
    --hash=sha256:bbbb
idna==3.7 --hash=sha256:cccc
plain==1.0
`)
	wantPin(t, f, "requests", "2.32.0", "sha256:aaaa sha256:bbbb", "")
	wantPin(t, f, "idna", "3.7", "sha256:cccc", "")
	wantPin(t, f, "plain", "1.0", "", "")
}

func TestGemfileRemotePins(t *testing.T) {
	f := mustParse(t, "Gemfile.lock", `GEM
  remote: https://rubygems.org/
  specs:
    rack (3.1.0)

GEM
  remote: https://gems.corp.internal/
  specs:
    internal-gem (1.0.0)

DEPENDENCIES
  rack
  internal-gem
`)
	wantPin(t, f, "rack", "3.1.0", "", "rubygems.org")
	wantPin(t, f, "internal-gem", "1.0.0", "", "gems.corp.internal")
}

func TestNpmV1Pins(t *testing.T) {
	f := mustParse(t, "package-lock.json", `{
  "lockfileVersion": 1,
  "dependencies": {
    "left-pad": {
      "version": "1.3.0",
      "resolved": "https://registry.npmjs.org/left-pad/-/left-pad-1.3.0.tgz",
      "integrity": "sha1-9zqFudXUHQRVUcF34ogtSshXKKY="
    }
  }
}`)
	wantPin(t, f, "left-pad", "1.3.0", "sha1-9zqFudXUHQRVUcF34ogtSshXKKY=", "registry.npmjs.org")
}
