package lock

import (
	"strings"
	"testing"
)

// uv shape: inline sdist/wheels tables, multi-line wheels arrays.
const pylockUV = `# autogenerated by uv
lock-version = "1.0"
created-by = "uv"
requires-python = ">=3.12"

[[packages]]
name = "alabaster"
version = "1.0.0"
sdist = { url = "https://files.pythonhosted.org/packages/a6/f8/alabaster-1.0.0.tar.gz", upload-time = 2024-07-26T18:15:03Z, size = 24210, hashes = { sha256 = "c00dca57bca26fa62a6d7d0a9fcce65f3e026e9bfe33e9c538fd3fbb2144fd9e" } }
wheels = [{ url = "https://files.pythonhosted.org/packages/7e/b3/alabaster-1.0.0-py3-none-any.whl", upload-time = 2024-07-26T18:15:02Z, size = 13929, hashes = { sha256 = "fc6786402dc3fcb2de3cabd5fe455a2db534b371124f1f21de8731783dec828b" } }]

[[packages]]
name = "charset-normalizer"
version = "3.4.7"
sdist = { url = "https://files.pythonhosted.org/packages/e7/a1/charset_normalizer-3.4.7.tar.gz", upload-time = 2026-04-02T09:28:39Z, size = 144271, hashes = { sha256 = "ae89db9e5f98a11a4bf50407d4363e7b09b31e55bc117b4f7d80aab97ba009e5" } }
wheels = [
    { url = "https://files.pythonhosted.org/packages/0c/eb/charset_normalizer-3.4.7-cp312-macosx.whl", upload-time = 2026-04-02T09:26:24Z, size = 311328, hashes = { sha256 = "eca9705049ad3c7345d574e3510665cb2cf844c2f2dcfe675332677f081cbd46" } },
    { url = "https://files.pythonhosted.org/packages/f8/e3/charset_normalizer-3.4.7-cp312-linux.whl", upload-time = 2026-04-02T09:26:25Z, size = 208061, hashes = { sha256 = "6178f72c5508bfc5fd446a5905e698c6212932f25bcdd4b47a757a50605a90e2" } },
]

[[packages]]
name = "mylib"
version = "0.9.0"
vcs = { type = "git", url = "https://github.com/example/mylib", commit-id = "abc123def456abc123def456abc123def456ab12" }
`

// pip shape: [[packages.wheels]] sub-tables with their own name keys and
// [packages.wheels.hashes] sub-sub-tables.
const pylockPip = `lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "build"
version = "1.5.0"

[[packages.wheels]]
name = "build-1.5.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/0d/fe/build-1.5.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "13f3eecb844759ab66efec90ca17639bbf14dc06cb2fdf37a9010322d9c50a6f"

[[packages]]
name = "flit-core"
version = "3.12.0"

[[packages.wheels]]
name = "flit_core-3.12.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/f2/65/flit_core-3.12.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "e7a0304069ea895172e3c7bb703292e992c5d1555dd1233ab7b5621b5b69e62c"
`

// pipenv shape: index key + multi-line inline wheels arrays; plus a
// directory sub-table, a local-path wheel, and a dependencies array.
const pylockPipenv = `lock-version = "1.0"
environments = []
created-by = "pipenv"

[[packages]]
name = "attrs"
version = "25.4.0"
marker = "python_version >= '3.9'"
index = "https://pypi.org/simple/"
wheels = [
    {name = "attrs-25.4.0-py3-none-any.whl", url = "https://pypi.org/simple/attrs/attrs-25.4.0-py3-none-any.whl", hashes = {sha256 = "16d5969b87f0859ef33a48b35d55ac1be6e42ae49d5e853b597db70c35c57e11"}},
]

[[packages]]
name = "internal-api"
version = "2.0.0"
index = "https://pypi.corp.example/simple/"
wheels = [
    {name = "internal_api-2.0.0-py3-none-any.whl", url = "https://pypi.corp.example/packages/internal_api-2.0.0-py3-none-any.whl", hashes = {sha256 = "aaaa969b87f0859ef33a48b35d55ac1be6e42ae49d5e853b597db70c35c57e11"}},
]
dependencies = [{name = "attrs"}, {name = "vendored-wheel"}]

[[packages]]
name = "myproject"
version = "1.0.0"

[packages.directory]
path = "."
editable = true

[[packages]]
name = "vendored-wheel"
version = "4.2.1"
wheels = [
    {name = "vendored_wheel-4.2.1-py3-none-any.whl", path = "wheels/vendored_wheel-4.2.1-py3-none-any.whl", hashes = {sha256 = "bbbb969b87f0859ef33a48b35d55ac1be6e42ae49d5e853b597db70c35c57e11"}},
]

[[packages]]
name = "tool-cfg"
version = "0.1.0"
index = "https://pypi.org/simple/"

[packages.tool.pdm]
name = "should-not-leak"
`

func TestPylockUV(t *testing.T) {
	f, err := parsePylock("pylock.toml", []byte(pylockUV))
	if err != nil {
		t.Fatal(err)
	}
	if got := f.Packages["alabaster"]; len(got) != 1 || got[0] != "1.0.0" {
		t.Fatalf("alabaster = %v", got)
	}
	if got := f.Packages["charset-normalizer"]; len(got) != 1 || got[0] != "3.4.7" {
		t.Fatalf("charset-normalizer = %v", got)
	}
	pin := f.Pin("alabaster", "1.0.0")
	if pin.Host != "files.pythonhosted.org" {
		t.Fatalf("alabaster host = %q", pin.Host)
	}
	if want := "sha256:c00dca57bca26fa62a6d7d0a9fcce65f3e026e9bfe33e9c538fd3fbb2144fd9e sha256:fc6786402dc3fcb2de3cabd5fe455a2db534b371124f1f21de8731783dec828b"; pin.Integrity != want {
		t.Fatalf("alabaster integrity = %q", pin.Integrity)
	}
	// multi-line wheels array: all hashes accumulate
	if pin := f.Pin("charset-normalizer", "3.4.7"); len(strings.Fields(pin.Integrity)) != 3 {
		t.Fatalf("charset-normalizer integrity = %q", pin.Integrity)
	}
	// vcs source: recorded but non-registry
	if got := f.Packages["mylib"]; len(got) != 1 || got[0] != "0.9.0" {
		t.Fatalf("mylib = %v", got)
	}
	if !f.NonRegistry["mylib"] {
		t.Fatal("mylib (vcs) should be NonRegistry")
	}
	if f.NonRegistry["alabaster"] {
		t.Fatal("alabaster should be registry")
	}
}

func TestPylockPip(t *testing.T) {
	f, err := parsePylock("pylock.toml", []byte(pylockPip))
	if err != nil {
		t.Fatal(err)
	}
	if len(f.Packages) != 2 {
		t.Fatalf("packages = %v", f.Packages)
	}
	// wheel sub-table name keys must not clobber the package name
	if _, ok := f.Packages["build-1.5.0-py3-none-any.whl"]; ok {
		t.Fatal("wheel filename leaked as a package name")
	}
	if got := f.Packages["build"]; len(got) != 1 || got[0] != "1.5.0" {
		t.Fatalf("build = %v", got)
	}
	pin := f.Pin("build", "1.5.0")
	if pin.Integrity != "sha256:13f3eecb844759ab66efec90ca17639bbf14dc06cb2fdf37a9010322d9c50a6f" {
		t.Fatalf("build integrity = %q", pin.Integrity)
	}
	if pin.Host != "files.pythonhosted.org" {
		t.Fatalf("build host = %q", pin.Host)
	}
}

func TestPylockPipenv(t *testing.T) {
	f, err := parsePylock("pylock.toml", []byte(pylockPipenv))
	if err != nil {
		t.Fatal(err)
	}
	// index host wins over artifact host
	if pin := f.Pin("attrs", "25.4.0"); pin.Host != "pypi.org" {
		t.Fatalf("attrs host = %q", pin.Host)
	}
	// alternate index recorded (dependency-confusion signal), still registryish
	if pin := f.Pin("internal-api", "2.0.0"); pin.Host != "pypi.corp.example" {
		t.Fatalf("internal-api host = %q", pin.Host)
	}
	// dependencies array → graph edges
	deps := f.Deps["internal-api"]
	if len(deps) != 2 || deps[0] != "attrs" || deps[1] != "vendored-wheel" {
		t.Fatalf("internal-api deps = %v", deps)
	}
	// directory source (the project itself) → NonRegistry
	if !f.NonRegistry["myproject"] {
		t.Fatal("myproject (directory) should be NonRegistry")
	}
	// local-path-only wheel → NonRegistry
	if !f.NonRegistry["vendored-wheel"] {
		t.Fatal("vendored-wheel (path only) should be NonRegistry")
	}
	// [packages.tool.*] name keys must not leak
	if _, ok := f.Packages["should-not-leak"]; ok {
		t.Fatal("tool sub-table name leaked")
	}
	if got := f.Packages["tool-cfg"]; len(got) != 1 || got[0] != "0.1.0" {
		t.Fatalf("tool-cfg = %v", got)
	}
	if f.RootsKnown {
		t.Fatal("PEP 751 records no roots")
	}
}

func TestPylockByBasename(t *testing.T) {
	for _, name := range []string{"pylock.toml", "pylock.dev.toml", "a/b/pylock.toml", `C:\proj\pylock.toml`} {
		p := ByBasename(name)
		if p == nil || p.Kind != "pylock.toml" {
			t.Fatalf("ByBasename(%q) = %v", name, p)
		}
	}
	for _, name := range []string{"pylock.toml.bak", "notpylock.toml"} {
		if p := ByBasename(name); p != nil && p.Kind == "pylock.toml" {
			t.Fatalf("ByBasename(%q) matched pylock", name)
		}
	}
}
